@startuml
entity Chat {
* pk
__
*created_at: datetime <<generated>>
updated_at: datetime <<generated>>
}

entity Message {
* pk
__
*author_id: number <<FK>>
*chat_id: number <<FK>>
reply_to: number <<FK>>
text: text
picture: path
*sent_at: datetime <<generated>>
}

entity User {
* pk
__
*email: text
*password: text
*registered_date: Date <<generated>>
name: text
surname: text
updated_date: Date
profile_picture: path
}

entity ChatUser {
* pk
__
* chat_id: Number <<FK>>
* user_id: Number <<FK>>
}


ChatUser }|-- User
ChatUser }|-- Chat


Message }|-- User
Message }|-- Chat
@enduml